// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.6.0.0
//    <NameSpace>IntelliTrace.Config</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><PascalCase>False</PascalCase><BaseClassName>EntityBase</BaseClassName><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><InitializeFields>All</InitializeFields><GenerateAllTypes>True</GenerateAllTypes>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace IntelliTrace.Config
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas-microsoft-com:visualstudio:tracelog")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="urn:schemas-microsoft-com:visualstudio:tracelog", IsNullable=false)]
    public partial class CollectionPlan
    {
        
        private CollectionPlanStartupInfo startupInfoField;
        
        private CollectionPlanCheckpointOptions checkpointOptionsField;
        
        private CollectionPlanTraceInstrumentation traceInstrumentationField;
        
        private CollectionPlanDetourInstrumentation detourInstrumentationField;
        
        private CollectionPlanCoverageInstrumentation coverageInstrumentationField;
        
        private CollectionPlanDiagnosticEventInstrumentation diagnosticEventInstrumentationField;
        
        private CollectionPlanWebRequestTrackingInstrumentation webRequestTrackingInstrumentationField;
        
        private CollectionPlanWebTrackingInstrumentation webTrackingInstrumentationField;
        
        private CollectionPlanUnitTestIsolationInstrumentation unitTestIsolationInstrumentationField;
        
        private CollectionPlanTracePointProvider tracePointProviderField;
        
        public CollectionPlan()
        {
            this.tracePointProviderField = new CollectionPlanTracePointProvider();
            this.unitTestIsolationInstrumentationField = new CollectionPlanUnitTestIsolationInstrumentation();
            this.webTrackingInstrumentationField = new CollectionPlanWebTrackingInstrumentation();
            this.webRequestTrackingInstrumentationField = new CollectionPlanWebRequestTrackingInstrumentation();
            this.diagnosticEventInstrumentationField = new CollectionPlanDiagnosticEventInstrumentation();
            this.coverageInstrumentationField = new CollectionPlanCoverageInstrumentation();
            this.detourInstrumentationField = new CollectionPlanDetourInstrumentation();
            this.traceInstrumentationField = new CollectionPlanTraceInstrumentation();
            this.checkpointOptionsField = new CollectionPlanCheckpointOptions();
            this.startupInfoField = new CollectionPlanStartupInfo();
        }
        
        public CollectionPlanStartupInfo StartupInfo
        {
            get
            {
                return this.startupInfoField;
            }
            set
            {
                this.startupInfoField = value;
            }
        }
        
        public CollectionPlanCheckpointOptions CheckpointOptions
        {
            get
            {
                return this.checkpointOptionsField;
            }
            set
            {
                this.checkpointOptionsField = value;
            }
        }
        
        public CollectionPlanTraceInstrumentation TraceInstrumentation
        {
            get
            {
                return this.traceInstrumentationField;
            }
            set
            {
                this.traceInstrumentationField = value;
            }
        }
        
        public CollectionPlanDetourInstrumentation DetourInstrumentation
        {
            get
            {
                return this.detourInstrumentationField;
            }
            set
            {
                this.detourInstrumentationField = value;
            }
        }
        
        public CollectionPlanCoverageInstrumentation CoverageInstrumentation
        {
            get
            {
                return this.coverageInstrumentationField;
            }
            set
            {
                this.coverageInstrumentationField = value;
            }
        }
        
        public CollectionPlanDiagnosticEventInstrumentation DiagnosticEventInstrumentation
        {
            get
            {
                return this.diagnosticEventInstrumentationField;
            }
            set
            {
                this.diagnosticEventInstrumentationField = value;
            }
        }
        
        public CollectionPlanWebRequestTrackingInstrumentation WebRequestTrackingInstrumentation
        {
            get
            {
                return this.webRequestTrackingInstrumentationField;
            }
            set
            {
                this.webRequestTrackingInstrumentationField = value;
            }
        }
        
        public CollectionPlanWebTrackingInstrumentation WebTrackingInstrumentation
        {
            get
            {
                return this.webTrackingInstrumentationField;
            }
            set
            {
                this.webTrackingInstrumentationField = value;
            }
        }
        
        public CollectionPlanUnitTestIsolationInstrumentation UnitTestIsolationInstrumentation
        {
            get
            {
                return this.unitTestIsolationInstrumentationField;
            }
            set
            {
                this.unitTestIsolationInstrumentationField = value;
            }
        }
        
        public CollectionPlanTracePointProvider TracePointProvider
        {
            get
            {
                return this.tracePointProviderField;
            }
            set
            {
                this.tracePointProviderField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas-microsoft-com:visualstudio:tracelog")]
    public partial class CollectionPlanStartupInfo
    {
        
        private object logFileNameField;
        
        private object logFileDirectoryField;
        
        private ushort maximumLogFileSizeField;
        
        public object LogFileName
        {
            get
            {
                return this.logFileNameField;
            }
            set
            {
                this.logFileNameField = value;
            }
        }
        
        public object LogFileDirectory
        {
            get
            {
                return this.logFileDirectoryField;
            }
            set
            {
                this.logFileDirectoryField = value;
            }
        }
        
        public ushort MaximumLogFileSize
        {
            get
            {
                return this.maximumLogFileSizeField;
            }
            set
            {
                this.maximumLogFileSizeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas-microsoft-com:visualstudio:tracelog")]
    public partial class CollectionPlanCheckpointOptions
    {
        
        private CollectionPlanCheckpointOptionsThreadCheckpoints threadCheckpointsField;
        
        private CollectionPlanCheckpointOptionsNotifyPointCheckpoints notifyPointCheckpointsField;
        
        public CollectionPlanCheckpointOptions()
        {
            this.notifyPointCheckpointsField = new CollectionPlanCheckpointOptionsNotifyPointCheckpoints();
            this.threadCheckpointsField = new CollectionPlanCheckpointOptionsThreadCheckpoints();
        }
        
        public CollectionPlanCheckpointOptionsThreadCheckpoints ThreadCheckpoints
        {
            get
            {
                return this.threadCheckpointsField;
            }
            set
            {
                this.threadCheckpointsField = value;
            }
        }
        
        public CollectionPlanCheckpointOptionsNotifyPointCheckpoints NotifyPointCheckpoints
        {
            get
            {
                return this.notifyPointCheckpointsField;
            }
            set
            {
                this.notifyPointCheckpointsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas-microsoft-com:visualstudio:tracelog")]
    public partial class CollectionPlanCheckpointOptionsThreadCheckpoints
    {
        
        private string modeField;
        
        private ushort startRateField;
        
        public string Mode
        {
            get
            {
                return this.modeField;
            }
            set
            {
                this.modeField = value;
            }
        }
        
        public ushort StartRate
        {
            get
            {
                return this.startRateField;
            }
            set
            {
                this.startRateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas-microsoft-com:visualstudio:tracelog")]
    public partial class CollectionPlanCheckpointOptionsNotifyPointCheckpoints
    {
        
        private string modeField;
        
        private ushort startRateField;
        
        public string Mode
        {
            get
            {
                return this.modeField;
            }
            set
            {
                this.modeField = value;
            }
        }
        
        public ushort StartRate
        {
            get
            {
                return this.startRateField;
            }
            set
            {
                this.startRateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas-microsoft-com:visualstudio:tracelog")]
    public partial class CollectionPlanTraceInstrumentation
    {
        
        private string optionsField;
        
        private CollectionPlanTraceInstrumentationModuleList moduleListField;
        
        private CollectionPlanTraceInstrumentationProcessList processListField;
        
        private bool enabledField;
        
        public CollectionPlanTraceInstrumentation()
        {
            this.processListField = new CollectionPlanTraceInstrumentationProcessList();
            this.moduleListField = new CollectionPlanTraceInstrumentationModuleList();
        }
        
        public string Options
        {
            get
            {
                return this.optionsField;
            }
            set
            {
                this.optionsField = value;
            }
        }
        
        public CollectionPlanTraceInstrumentationModuleList ModuleList
        {
            get
            {
                return this.moduleListField;
            }
            set
            {
                this.moduleListField = value;
            }
        }
        
        public CollectionPlanTraceInstrumentationProcessList ProcessList
        {
            get
            {
                return this.processListField;
            }
            set
            {
                this.processListField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool enabled
        {
            get
            {
                return this.enabledField;
            }
            set
            {
                this.enabledField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas-microsoft-com:visualstudio:tracelog")]
    public partial class CollectionPlanTraceInstrumentationModuleList
    {
        
        private List<string> nameField;
        
        private bool isExclusionListField;
        
        public CollectionPlanTraceInstrumentationModuleList()
        {
            this.nameField = new List<string>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Name")]
        public List<string> Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isExclusionList
        {
            get
            {
                return this.isExclusionListField;
            }
            set
            {
                this.isExclusionListField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas-microsoft-com:visualstudio:tracelog")]
    public partial class CollectionPlanTraceInstrumentationProcessList
    {
        
        private List<string> nameField;
        
        private bool isExclusionListField;
        
        public CollectionPlanTraceInstrumentationProcessList()
        {
            this.nameField = new List<string>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Name")]
        public List<string> Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isExclusionList
        {
            get
            {
                return this.isExclusionListField;
            }
            set
            {
                this.isExclusionListField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas-microsoft-com:visualstudio:tracelog")]
    public partial class CollectionPlanDetourInstrumentation
    {
        
        private CollectionPlanDetourInstrumentationModuleList moduleListField;
        
        private CollectionPlanDetourInstrumentationProcessList processListField;
        
        private bool enabledField;
        
        public CollectionPlanDetourInstrumentation()
        {
            this.processListField = new CollectionPlanDetourInstrumentationProcessList();
            this.moduleListField = new CollectionPlanDetourInstrumentationModuleList();
        }
        
        public CollectionPlanDetourInstrumentationModuleList ModuleList
        {
            get
            {
                return this.moduleListField;
            }
            set
            {
                this.moduleListField = value;
            }
        }
        
        public CollectionPlanDetourInstrumentationProcessList ProcessList
        {
            get
            {
                return this.processListField;
            }
            set
            {
                this.processListField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool enabled
        {
            get
            {
                return this.enabledField;
            }
            set
            {
                this.enabledField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas-microsoft-com:visualstudio:tracelog")]
    public partial class CollectionPlanDetourInstrumentationModuleList
    {
        
        private bool isExclusionListField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isExclusionList
        {
            get
            {
                return this.isExclusionListField;
            }
            set
            {
                this.isExclusionListField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas-microsoft-com:visualstudio:tracelog")]
    public partial class CollectionPlanDetourInstrumentationProcessList
    {
        
        private bool isExclusionListField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isExclusionList
        {
            get
            {
                return this.isExclusionListField;
            }
            set
            {
                this.isExclusionListField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas-microsoft-com:visualstudio:tracelog")]
    public partial class CollectionPlanCoverageInstrumentation
    {
        
        private bool enabledField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool enabled
        {
            get
            {
                return this.enabledField;
            }
            set
            {
                this.enabledField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas-microsoft-com:visualstudio:tracelog")]
    public partial class CollectionPlanDiagnosticEventInstrumentation
    {
        
        private CollectionPlanDiagnosticEventInstrumentationModuleList moduleListField;
        
        private CollectionPlanDiagnosticEventInstrumentationProcessList processListField;
        
        private bool enabledField;
        
        public CollectionPlanDiagnosticEventInstrumentation()
        {
            this.processListField = new CollectionPlanDiagnosticEventInstrumentationProcessList();
            this.moduleListField = new CollectionPlanDiagnosticEventInstrumentationModuleList();
        }
        
        public CollectionPlanDiagnosticEventInstrumentationModuleList ModuleList
        {
            get
            {
                return this.moduleListField;
            }
            set
            {
                this.moduleListField = value;
            }
        }
        
        public CollectionPlanDiagnosticEventInstrumentationProcessList ProcessList
        {
            get
            {
                return this.processListField;
            }
            set
            {
                this.processListField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool enabled
        {
            get
            {
                return this.enabledField;
            }
            set
            {
                this.enabledField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas-microsoft-com:visualstudio:tracelog")]
    public partial class CollectionPlanDiagnosticEventInstrumentationModuleList
    {
        
        private bool isExclusionListField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isExclusionList
        {
            get
            {
                return this.isExclusionListField;
            }
            set
            {
                this.isExclusionListField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas-microsoft-com:visualstudio:tracelog")]
    public partial class CollectionPlanDiagnosticEventInstrumentationProcessList
    {
        
        private List<string> nameField;
        
        private bool isExclusionListField;
        
        public CollectionPlanDiagnosticEventInstrumentationProcessList()
        {
            this.nameField = new List<string>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Name")]
        public List<string> Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isExclusionList
        {
            get
            {
                return this.isExclusionListField;
            }
            set
            {
                this.isExclusionListField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas-microsoft-com:visualstudio:tracelog")]
    public partial class CollectionPlanWebRequestTrackingInstrumentation
    {
        
        private CollectionPlanWebRequestTrackingInstrumentationProcessList processListField;
        
        private bool enabledField;
        
        public CollectionPlanWebRequestTrackingInstrumentation()
        {
            this.processListField = new CollectionPlanWebRequestTrackingInstrumentationProcessList();
        }
        
        public CollectionPlanWebRequestTrackingInstrumentationProcessList ProcessList
        {
            get
            {
                return this.processListField;
            }
            set
            {
                this.processListField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool enabled
        {
            get
            {
                return this.enabledField;
            }
            set
            {
                this.enabledField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas-microsoft-com:visualstudio:tracelog")]
    public partial class CollectionPlanWebRequestTrackingInstrumentationProcessList
    {
        
        private List<string> nameField;
        
        private bool isExclusionListField;
        
        public CollectionPlanWebRequestTrackingInstrumentationProcessList()
        {
            this.nameField = new List<string>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Name")]
        public List<string> Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isExclusionList
        {
            get
            {
                return this.isExclusionListField;
            }
            set
            {
                this.isExclusionListField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas-microsoft-com:visualstudio:tracelog")]
    public partial class CollectionPlanWebTrackingInstrumentation
    {
        
        private CollectionPlanWebTrackingInstrumentationProcessList processListField;
        
        private bool enabledField;
        
        public CollectionPlanWebTrackingInstrumentation()
        {
            this.processListField = new CollectionPlanWebTrackingInstrumentationProcessList();
        }
        
        public CollectionPlanWebTrackingInstrumentationProcessList ProcessList
        {
            get
            {
                return this.processListField;
            }
            set
            {
                this.processListField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool enabled
        {
            get
            {
                return this.enabledField;
            }
            set
            {
                this.enabledField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas-microsoft-com:visualstudio:tracelog")]
    public partial class CollectionPlanWebTrackingInstrumentationProcessList
    {
        
        private bool isExclusionListField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isExclusionList
        {
            get
            {
                return this.isExclusionListField;
            }
            set
            {
                this.isExclusionListField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas-microsoft-com:visualstudio:tracelog")]
    public partial class CollectionPlanUnitTestIsolationInstrumentation
    {
        
        private CollectionPlanUnitTestIsolationInstrumentationProcessList processListField;
        
        private bool enabledField;
        
        public CollectionPlanUnitTestIsolationInstrumentation()
        {
            this.processListField = new CollectionPlanUnitTestIsolationInstrumentationProcessList();
        }
        
        public CollectionPlanUnitTestIsolationInstrumentationProcessList ProcessList
        {
            get
            {
                return this.processListField;
            }
            set
            {
                this.processListField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool enabled
        {
            get
            {
                return this.enabledField;
            }
            set
            {
                this.enabledField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas-microsoft-com:visualstudio:tracelog")]
    public partial class CollectionPlanUnitTestIsolationInstrumentationProcessList
    {
        
        private bool isExclusionListField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isExclusionList
        {
            get
            {
                return this.isExclusionListField;
            }
            set
            {
                this.isExclusionListField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas-microsoft-com:visualstudio:tracelog")]
    public partial class CollectionPlanTracePointProvider
    {
        
        private List<CollectionPlanTracePointProviderCategory> categoriesField;
        
        private List<CollectionPlanTracePointProviderModuleSpecification> moduleSpecificationsField;
        
        private List<CollectionPlanTracePointProviderDiagnosticEventSpecification> diagnosticEventSpecificationsField;
        
        public CollectionPlanTracePointProvider()
        {
            this.diagnosticEventSpecificationsField = new List<CollectionPlanTracePointProviderDiagnosticEventSpecification>();
            this.moduleSpecificationsField = new List<CollectionPlanTracePointProviderModuleSpecification>();
            this.categoriesField = new List<CollectionPlanTracePointProviderCategory>();
        }
        
        [System.Xml.Serialization.XmlArrayItemAttribute("Category", IsNullable=false)]
        public List<CollectionPlanTracePointProviderCategory> Categories
        {
            get
            {
                return this.categoriesField;
            }
            set
            {
                this.categoriesField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayItemAttribute("ModuleSpecification", IsNullable=false)]
        public List<CollectionPlanTracePointProviderModuleSpecification> ModuleSpecifications
        {
            get
            {
                return this.moduleSpecificationsField;
            }
            set
            {
                this.moduleSpecificationsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayItemAttribute("DiagnosticEventSpecification", IsNullable=false)]
        public List<CollectionPlanTracePointProviderDiagnosticEventSpecification> DiagnosticEventSpecifications
        {
            get
            {
                return this.diagnosticEventSpecificationsField;
            }
            set
            {
                this.diagnosticEventSpecificationsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas-microsoft-com:visualstudio:tracelog")]
    public partial class CollectionPlanTracePointProviderCategory
    {
        
        private string idField;
        
        private string _locIDField;
        
        private string valueField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string _locID
        {
            get
            {
                return this._locIDField;
            }
            set
            {
                this._locIDField = value;
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas-microsoft-com:visualstudio:tracelog")]
    public partial class CollectionPlanTracePointProviderModuleSpecification
    {
        
        private string idField;
        
        private string maxVersionField;
        
        private string minVersionField;
        
        private string valueField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string maxVersion
        {
            get
            {
                return this.maxVersionField;
            }
            set
            {
                this.maxVersionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string minVersion
        {
            get
            {
                return this.minVersionField;
            }
            set
            {
                this.minVersionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas-microsoft-com:visualstudio:tracelog")]
    public partial class CollectionPlanTracePointProviderDiagnosticEventSpecification
    {
        
        private string categoryIdField;
        
        private CollectionPlanTracePointProviderDiagnosticEventSpecificationSettingsName settingsNameField;
        
        private CollectionPlanTracePointProviderDiagnosticEventSpecificationSettingsDescription settingsDescriptionField;
        
        private List<CollectionPlanTracePointProviderDiagnosticEventSpecificationBinding> bindingsField;
        
        private System.Nullable<bool> enabledField;
        
        public CollectionPlanTracePointProviderDiagnosticEventSpecification()
        {
            this.bindingsField = new List<CollectionPlanTracePointProviderDiagnosticEventSpecificationBinding>();
            this.settingsDescriptionField = new CollectionPlanTracePointProviderDiagnosticEventSpecificationSettingsDescription();
            this.settingsNameField = new CollectionPlanTracePointProviderDiagnosticEventSpecificationSettingsName();
        }
        
        public string CategoryId
        {
            get
            {
                return this.categoryIdField;
            }
            set
            {
                this.categoryIdField = value;
            }
        }
        
        public CollectionPlanTracePointProviderDiagnosticEventSpecificationSettingsName SettingsName
        {
            get
            {
                return this.settingsNameField;
            }
            set
            {
                this.settingsNameField = value;
            }
        }
        
        public CollectionPlanTracePointProviderDiagnosticEventSpecificationSettingsDescription SettingsDescription
        {
            get
            {
                return this.settingsDescriptionField;
            }
            set
            {
                this.settingsDescriptionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayItemAttribute("Binding", IsNullable=false)]
        public List<CollectionPlanTracePointProviderDiagnosticEventSpecificationBinding> Bindings
        {
            get
            {
                return this.bindingsField;
            }
            set
            {
                this.bindingsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool enabled
        {
            get
            {
                if (this.enabledField.HasValue)
                {
                    return this.enabledField.Value;
                }
                else
                {
                    return default(bool);
                }
            }
            set
            {
                this.enabledField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool enabledSpecified
        {
            get
            {
                return this.enabledField.HasValue;
            }
            set
            {
                if (value==false)
                {
                    this.enabledField = null;
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas-microsoft-com:visualstudio:tracelog")]
    public partial class CollectionPlanTracePointProviderDiagnosticEventSpecificationSettingsName
    {
        
        private string _locIDField;
        
        private string valueField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string _locID
        {
            get
            {
                return this._locIDField;
            }
            set
            {
                this._locIDField = value;
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas-microsoft-com:visualstudio:tracelog")]
    public partial class CollectionPlanTracePointProviderDiagnosticEventSpecificationSettingsDescription
    {
        
        private string _locIDField;
        
        private string valueField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string _locID
        {
            get
            {
                return this._locIDField;
            }
            set
            {
                this._locIDField = value;
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas-microsoft-com:visualstudio:tracelog")]
    public partial class CollectionPlanTracePointProviderDiagnosticEventSpecificationBinding
    {
        
        private string moduleSpecificationIdField;
        
        private string typeNameField;
        
        private string methodNameField;
        
        private string methodIdField;
        
        private CollectionPlanTracePointProviderDiagnosticEventSpecificationBindingProgrammableDataQuery programmableDataQueryField;
        
        private CollectionPlanTracePointProviderDiagnosticEventSpecificationBindingShortDescription shortDescriptionField;
        
        private CollectionPlanTracePointProviderDiagnosticEventSpecificationBindingLongDescription longDescriptionField;
        
        private List<CollectionPlanTracePointProviderDiagnosticEventSpecificationBindingDataQuery> dataQueriesField;
        
        private System.Nullable<bool> onReturnField;
        
        public CollectionPlanTracePointProviderDiagnosticEventSpecificationBinding()
        {
            this.dataQueriesField = new List<CollectionPlanTracePointProviderDiagnosticEventSpecificationBindingDataQuery>();
            this.longDescriptionField = new CollectionPlanTracePointProviderDiagnosticEventSpecificationBindingLongDescription();
            this.shortDescriptionField = new CollectionPlanTracePointProviderDiagnosticEventSpecificationBindingShortDescription();
            this.programmableDataQueryField = new CollectionPlanTracePointProviderDiagnosticEventSpecificationBindingProgrammableDataQuery();
        }
        
        public string ModuleSpecificationId
        {
            get
            {
                return this.moduleSpecificationIdField;
            }
            set
            {
                this.moduleSpecificationIdField = value;
            }
        }
        
        public string TypeName
        {
            get
            {
                return this.typeNameField;
            }
            set
            {
                this.typeNameField = value;
            }
        }
        
        public string MethodName
        {
            get
            {
                return this.methodNameField;
            }
            set
            {
                this.methodNameField = value;
            }
        }
        
        public string MethodId
        {
            get
            {
                return this.methodIdField;
            }
            set
            {
                this.methodIdField = value;
            }
        }
        
        public CollectionPlanTracePointProviderDiagnosticEventSpecificationBindingProgrammableDataQuery ProgrammableDataQuery
        {
            get
            {
                return this.programmableDataQueryField;
            }
            set
            {
                this.programmableDataQueryField = value;
            }
        }
        
        public CollectionPlanTracePointProviderDiagnosticEventSpecificationBindingShortDescription ShortDescription
        {
            get
            {
                return this.shortDescriptionField;
            }
            set
            {
                this.shortDescriptionField = value;
            }
        }
        
        public CollectionPlanTracePointProviderDiagnosticEventSpecificationBindingLongDescription LongDescription
        {
            get
            {
                return this.longDescriptionField;
            }
            set
            {
                this.longDescriptionField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayItemAttribute("DataQuery", IsNullable=false)]
        public List<CollectionPlanTracePointProviderDiagnosticEventSpecificationBindingDataQuery> DataQueries
        {
            get
            {
                return this.dataQueriesField;
            }
            set
            {
                this.dataQueriesField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool onReturn
        {
            get
            {
                if (this.onReturnField.HasValue)
                {
                    return this.onReturnField.Value;
                }
                else
                {
                    return default(bool);
                }
            }
            set
            {
                this.onReturnField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool onReturnSpecified
        {
            get
            {
                return this.onReturnField.HasValue;
            }
            set
            {
                if (value==false)
                {
                    this.onReturnField = null;
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas-microsoft-com:visualstudio:tracelog")]
    public partial class CollectionPlanTracePointProviderDiagnosticEventSpecificationBindingProgrammableDataQuery
    {
        
        private string moduleNameField;
        
        private string typeNameField;
        
        public string ModuleName
        {
            get
            {
                return this.moduleNameField;
            }
            set
            {
                this.moduleNameField = value;
            }
        }
        
        public string TypeName
        {
            get
            {
                return this.typeNameField;
            }
            set
            {
                this.typeNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas-microsoft-com:visualstudio:tracelog")]
    public partial class CollectionPlanTracePointProviderDiagnosticEventSpecificationBindingShortDescription
    {
        
        private string _locIDField;
        
        private string valueField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string _locID
        {
            get
            {
                return this._locIDField;
            }
            set
            {
                this._locIDField = value;
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas-microsoft-com:visualstudio:tracelog")]
    public partial class CollectionPlanTracePointProviderDiagnosticEventSpecificationBindingLongDescription
    {
        
        private string _locIDField;
        
        private string valueField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string _locID
        {
            get
            {
                return this._locIDField;
            }
            set
            {
                this._locIDField = value;
            }
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Xsd2Code", "3.6.0.20097")]
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:schemas-microsoft-com:visualstudio:tracelog")]
    public partial class CollectionPlanTracePointProviderDiagnosticEventSpecificationBindingDataQuery
    {
        
        private sbyte indexField;
        
        private System.Nullable<ushort> maxSizeField;
        
        private string typeField;
        
        private string nameField;
        
        private string _locIDField;
        
        private string _locAttrDataField;
        
        private string queryField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte index
        {
            get
            {
                return this.indexField;
            }
            set
            {
                this.indexField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ushort maxSize
        {
            get
            {
                if (this.maxSizeField.HasValue)
                {
                    return this.maxSizeField.Value;
                }
                else
                {
                    return default(ushort);
                }
            }
            set
            {
                this.maxSizeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxSizeSpecified
        {
            get
            {
                return this.maxSizeField.HasValue;
            }
            set
            {
                if (value==false)
                {
                    this.maxSizeField = null;
                }
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string _locID
        {
            get
            {
                return this._locIDField;
            }
            set
            {
                this._locIDField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string _locAttrData
        {
            get
            {
                return this._locAttrDataField;
            }
            set
            {
                this._locAttrDataField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string query
        {
            get
            {
                return this.queryField;
            }
            set
            {
                this.queryField = value;
            }
        }
    }
}
